services:
  db:
      image: postgres:latest
      restart: unless-stopped
      ports:
        - ${WBRS_DATABASE_PORT:-5432}:5432
      environment:
        POSTGRES_USER: ${WBRS_DATABASE_USER}
        POSTGRES_PASSWORD: ${WBRS_DATABASE_PASSWORD}
        POSTGRES_DB: ${WBRS_DATABASE_NAME}
      volumes:
        - db:/var/lib/postgresql/data

  pgadmin:
      image: dpage/pgadmin4
      environment:
        PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
        PGADMIN_DEFAULT_PASSWORD: "password"
      ports:
        - "8081:80"
      depends_on:
        - db
volumes:
  db: 
    driver: local
  pgadmin:
    driver: local